#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  find-duplicate-sha256.sh [DIRECTORY...]

Description:
  Recursively scans the provided directories (defaults to ".") for files
  generated by analyze-archive.sh (suffix ".sha256") and reports any SHA-256
  digests that appear more than once. Each duplicate lists the manifest file
  and the archived path associated with that digest so you can spot redundant
  content across archives quickly.

Options:
  -h, --help    Show this help message.
EOF
}

die() {
  printf 'Error: %s\n' "$1" >&2
  exit 2
}

SEP=$'\x1F'
declare -A HASH_COUNTS=()
declare -A HASH_LOCATIONS=()

record_entry() {
  local hash="$1" manifest="$2" entry="$3"
  HASH_COUNTS["$hash"]=$(( ${HASH_COUNTS["$hash"]:-0} + 1 ))
  if [[ -v HASH_LOCATIONS["$hash"] ]]; then
    HASH_LOCATIONS["$hash"]+=$'\n'"$manifest$SEP$entry"
  else
    HASH_LOCATIONS["$hash"]="$manifest$SEP$entry"
  fi
}

entries_recorded=0
lines_skipped=0

process_manifest() {
  local manifest="$1" line line_no=0 manifest_entries=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line_no=$((line_no + 1))
    line="${line%$'\r'}"
    [[ -z "$line" ]] && continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    if [[ "$line" =~ ^([[:xdigit:]]{64})[[:space:]][[:space:]]+(.+)$ ]]; then
      record_entry "${BASH_REMATCH[1]}" "$manifest" "${BASH_REMATCH[2]}"
      entries_recorded=$((entries_recorded + 1))
      manifest_entries=$((manifest_entries + 1))
    else
      lines_skipped=$((lines_skipped + 1))
      printf 'warning: %s:%d not recognized, skipping\n' "$manifest" "$line_no" >&2
    fi
  done <"$manifest"

  if [[ "$manifest_entries" -eq 0 ]]; then
    printf 'note: %s contained no recognizable entries\n' "$manifest" >&2
  fi
}

dirs=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --)
      shift
      break
      ;;
    -*)
      die "Unknown option: $1"
      ;;
    *)
      dirs+=("$1")
      shift
      ;;
  esac
done

if [[ $# -gt 0 ]]; then
  dirs+=("$@")
fi

if [[ "${#dirs[@]}" -eq 0 ]]; then
  dirs=(".")
fi

for dir in "${dirs[@]}"; do
  [[ -d "$dir" ]] || die "Directory not found: $dir"
done

manifests_scanned=0
while IFS= read -r -d '' manifest; do
  manifests_scanned=$((manifests_scanned + 1))
  process_manifest "$manifest"
done < <(find "${dirs[@]}" -type f -name '*.sha256' -print0)

if [[ "$manifests_scanned" -eq 0 ]]; then
  die "No .sha256 manifests found under the provided directory set."
fi

printf 'Scanned %d manifest(s); %d total entries (%d unique hashes). Skipped %d line(s).\n' \
  "$manifests_scanned" "$entries_recorded" "${#HASH_COUNTS[@]}" "$lines_skipped"

duplicate_hashes=()
for hash in "${!HASH_COUNTS[@]}"; do
  if (( HASH_COUNTS["$hash"] > 1 )); then
    duplicate_hashes+=("$hash")
  fi
done

if [[ "${#duplicate_hashes[@]}" -eq 0 ]]; then
  printf 'No duplicate SHA-256 entries found.\n'
  exit 0
fi

printf '\nDuplicate SHA-256 digests:\n'
IFS=$'\n' read -r -d '' -a duplicate_hashes < <(printf '%s\n' "${duplicate_hashes[@]}" | LC_ALL=C sort && printf '\0')

for hash in "${duplicate_hashes[@]}"; do
  printf '\nSHA256 %s (%d occurrences):\n' "$hash" "${HASH_COUNTS["$hash"]}"
  while IFS= read -r location || [[ -n "$location" ]]; do
    IFS=$SEP read -r manifest entry <<<"$location"
    printf '  - %s :: %s\n' "$manifest" "$entry"
  done <<<"${HASH_LOCATIONS["$hash"]}"
done
